// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfbhKPFXNpxLtL1mfCRbh1pmU-A7qiEM',
    appId: '1:730470715637:web:2fe96a227f9d41ff5475bc',
    messagingSenderId: '730470715637',
    projectId: 'lostfound-fe03f',
    authDomain: 'lostfound-fe03f.firebaseapp.com',
    storageBucket: 'lostfound-fe03f.appspot.com',
    measurementId: 'G-6RQ80ZC7W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSCib4Nx5JoGSYoDGm33hyB1sddRRULjU',
    appId: '1:730470715637:android:90d85ae9b3f9602e5475bc',
    messagingSenderId: '730470715637',
    projectId: 'lostfound-fe03f',
    storageBucket: 'lostfound-fe03f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxmmA-OTH86NweOR1FKY5rnlTF2_BjT_0',
    appId: '1:730470715637:ios:43d5ff16bf0753a35475bc',
    messagingSenderId: '730470715637',
    projectId: 'lostfound-fe03f',
    storageBucket: 'lostfound-fe03f.appspot.com',
    iosBundleId: 'com.example.lf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxmmA-OTH86NweOR1FKY5rnlTF2_BjT_0',
    appId: '1:730470715637:ios:43d5ff16bf0753a35475bc',
    messagingSenderId: '730470715637',
    projectId: 'lostfound-fe03f',
    storageBucket: 'lostfound-fe03f.appspot.com',
    iosBundleId: 'com.example.lf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHfbhKPFXNpxLtL1mfCRbh1pmU-A7qiEM',
    appId: '1:730470715637:web:6dad7ec14437372f5475bc',
    messagingSenderId: '730470715637',
    projectId: 'lostfound-fe03f',
    authDomain: 'lostfound-fe03f.firebaseapp.com',
    storageBucket: 'lostfound-fe03f.appspot.com',
    measurementId: 'G-Y0KYRX1H0E',
  );
}
